<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BetterDOCX.Model\BetterDOCX.Model.csproj" />
    <ProjectReference Include="..\BetterDOCX.Design\BetterDOCX.Design.csproj" />
    <ProjectReference Include="..\BetterDOCX.OpenXml\BetterDOCX.OpenXml.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
